[package]
name = "tst"
version = "0.1.0"
authors = ["juhnowski <juhnowski@gmail.com>"]
edition = "2018"

[dependencies]
glib = "0.10.3"
gtk = "0.9.2"
gio = "0.9.1"
log = "0.4"
log4rs = "0.13.0"
rusqlite = "0.24.1"