[package]
name = "tst"
version = "0.1.0"
authors = ["juhnowski <juhnowski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { git = "https://github.com/gtk-rs/gtk.git" }
log = "0.4"
log4rs = "0.13.0"